---
title: "POLS 2003 Introduction to Public Policy"
format: html
---
Acadia University students in POLS 2003: Introduction to Public Policy have had the opportunity to research the social determinants of health faced by Indigenous communities in Canada. These reports highlight the importance of early education for Indigenous children. Although our focus is on issues faced by Indigenous communities, we want to emphasize that, as non-Indigenous researchers, it would be unethical for us to make policy recommendations because we cannot fully understand the needs and experiences of Indigenous peoples. We present this report simply as a summary of our research in an introductory public policy course.
In our research, we have prioritized listening to and learning from Indigenous voices. We have mainly used Indigenous sources, including the Assembly of First Nations, the Center for Indigenous Education, the First Nations Education Steering Committee, the Truth and Reconciliation Final Report, the Native Women’s Association of Canada, Dr. Piita Irniq, Brooke Paul, and Lara Hartman. Our team focused on gathering information from Indigenous news outlets, including The Turtle Island News, Inuit Tapiriit Kanatami, and APTN. Drafting this report has taught us the importance of exploring Indigenous policy ideas and perspectives.
This class has shown us the importance of learning from Indigenous experts, and we are honoured to have had the chance to do so through conversations with Indigenous policy experts, elders, and community members. We have engaged through Fall 2024 Kesalul!  ReconciliACTION Series. We sincerely thank the Indigenous policy experts who shared their knowledge and expertise with us, including Lara Hartman, Brooke Paul, Dr. Piita Irniq, and Cole Kippenhuck. We also thank CEWIL Canada for their generous grant to our class. Our gratitude extends to Dr. Cynthia Alexander and our class partner, Darlene Peters Copeland, for their valuable feedback, knowledge, and support. This course has enabled us to delve deeper and move beyond our usual sources.
Throughout this report, we have strived to further our decolonization journey and to understand the sources and their validity better.

<embed src="pols2003.pdf" type="application/pdf" width="100%" height="600px" />