---
title: "POLS 1303 Law, Politics & Government"
format: html
---
In POLS 1303: Introduction to Public Policy at Acadia University, students researched the social determinants of health in Indigenous communities, with a particular focus on the importance of early education. As non-Indigenous researchers, we recognize that it would be inappropriate to make policy recommendations, since we cannot fully represent Indigenous needs and experiences. These reports are therefore presented as a summary of our learning in the course.
Our research prioritized Indigenous perspectives, drawing on sources such as the Assembly of First Nations, the Truth and Reconciliation Commission Final Report, the Native Women’s Association of Canada, Indigenous scholars, and Indigenous media outlets like APTN News and The Turtle Island News. This process taught us the value of grounding public policy discussions in Indigenous voices and knowledge.
We are grateful for the opportunity to learn from Indigenous policy experts, Elders, and community members through initiatives in Fall 2024 Kesalul!  ReconciliACTION Series. Their guidance deepened our understanding of reconciliation and the ongoing impact of colonial policies. This project has enabled us to take further steps in our own decolonization journey while critically reflecting on the sources we use and the perspectives they represent.

<embed src="pols1303.pdf" type="application/pdf" width="100%" height="600px" />