---
title: "Fall 2024 Kesalul! ReconciliACTION Program Details"
format: 
  html:
    toc: true
    toc-location: right
    toc-title: "On this page"
    toc-depth: 3
---
Welcome to the program and photo gallery of the Fall 2024 Kesalul! ReconciliACTION Series. These images reflect the spirit of coming together—sharing stories, building connections, and learning from one another. We hope they bring back meaningful memories for those who joined us and invite others to feel the energy, joy, and commitment that guided this journey.



# **Foundational Acadia University Students’ Policy Dialogues with Indigenous Experts**

## **September 19^th^, 2024**

-   **Title:** Personal Safety and Security of Indigenous Women and Children

-   **Moderator:** Darlene Peters Copeland

-   **Location:** KCIC Gardens

-   **Indigenous Experts:**

**Elder Dr. Lorraine Peters-Whitman**, **former President of the NWAC.**

“*Grand Mother White Sea turtle and President of Native Women Association of Canada. Grand Daughter of the late Chief Louis Peters and daughter of late Chief Joesph Peters and Elder Doris nee Brooks. Lorraine is one of fourteen children, seven brothers and six sisters. Born and raised in Middleton, Nova Scotia and graduated from Grant MacEwan Community College and University of Alberta as a Rehabilitation Practitioner. She is married to husband Thomas and have a daughter Zabrina.Lorraine had worked on her First Nation community of Glooscap for a total of 30 years, 17 years as an elected councillor, Social Development Officer, Education Councillor, and continued her education at Yellowquill College as a Diabetes Initiative Worker. In 2017 Lorraine was elected as the President of Nova Scotia Native Womens Association and in 2019 Lorraine was elected as the President for Native Women Association of Canada. Throughout her working career she has advocated and defending the rights for the Indigenous people and the women, girls and gender diverse community. Over the past 5 years she has concentrated on the Missing Murdered indigenous Women and Girls. Lorraine’s advocacy work and volunteerism has also been recognized by receiving her Honorary Doctorate of Humanities from Acadia University. “I feel very companionate about the work I do for equality and to STOP the violence and this can only be done through working together in being part of the solution.”*

**Brooke Paul, Supervisor, Mi’kmaw Family Healing Center.**

*“I am an Indigenous woman from the Glooscap First Nation. I have five beautiful children and a handsome husband whom I love very much. I have been working in the Domestic / Family Violence field for 16 years. I am the Program Supervisor for the Mi’kmaw Family Healing Centre, an Indigenous women’s transition house. When I am not working or on an adventure with my family I enjoy sleep and learning new things.”*

<embed src="sep19.pdf" type="application/pdf" width="100%" height="600px" />


## **September 26^th^, 2024**

-   **Title:** My Two Spirit Eyed Seeing Approach to Intersectionality

-   Students’ Partner and Mentor: Ann Sylliboy (virtually)

-   Location: Fountain Commons Great Hall

-   Indigenous Expert: **Cole Kippenhuck, Two Spirit Knowledge Holder**

*Cole Kippenhuck (they/them) is a Two Spirit Inuk Labradorian with 20+ years' experience in the community sector. They are the owner of Crow Kinship Consulting, a life coach, and an advocate for Indigenous, queer, and social justice issues. Cole is a part of the Newfoundland and Labrador Queer Research Initiative, Pearson Indigenous Advisory Circle, and the Newfoundland and Labrador Provincial Harm Reduction Collective. They are passionate about community engagement, trauma healing work, and organizational development. Cole holds ceremony, protects land, and walks in a spiritual way. They are fluid in their sexuality, gender, and relationships.*

## **September 27^th^, 2024**

-   Title: **Mandate of the Independent Special Interlocutor: A personal perspective.**

This presentation is designed to give participants a firsthand account of the work of the OSI in its support for the search for Missing Children and Unmarked Grave Sites. This conversation is designed to give participants an opportunity to learn a little on the background of Canada’s Indian Residential School System and identification of Unmarked Graves and Burial Sites. In addition to sharing the work to date, Laver will discuss his experiences and approach to engagement and contributions in establishing and building trust between Canada and First Nations, Inuit, and Metis peoples.

-   Students’ Partner and Mentor: Ann Sylliboy (MK)

-   Location: KCIC Classroom 14

-   Indigenous Expert: **Laver Simard,** Office of the Independent Special Interlocutor (OSI) for Missing Children and Unmarked Graves and Burial Sites associated with Indian Residential Schools.

*Grew up in the community of Manigotogan, MB and a member of the Hollow Water First Nation in Treaty 5 Territory. Family of twelve and proud father of daughter Janessa. June 2022- Appointed Director of Procurement and Protocols of the mandate of the Office of the Independent Special Interlocutor. June 2022- Seconded from PSPC to Office of Special Interlocutor for Missing Children and Unmarked Graves. January 2022; Seconded from PSPC to Department of Fisheries and Oceans (DFO)-Arctic Region-contributed to DFO Regional Reconciliation Action Plan. January 2015 to 2019- worked as PSPC Accommodation Manager. September 2019 to 2021-Seconded to National Centre for truth and Reconciliation (University of Manitoba) to support Governance implementation. June 2010 to December 2015-while working as a PSPC Supply Specialist, he was recruited to join the Truth and Reconciliation Commission of Canada (TRC). His role as TRC was the National Manager of Contracting and Finance. In addition to this role, he was asked by the Honorable Murray Sinclair, retired Senator and Chief Commissioner of the TRC to be responsible for the sacred and cultural items that TRC had in its possession and would accumulate over the mandate of the commission. This allowed him the opportunity to work closely with and learn from Residential School Survivors, Elders, Traditional Knowledge Keepers and Spiritual Advisors across Canada. His insight and experience on Reconciliation is unique given that he is the only Public Servant in Canada to work 5 years on the TRC. [Independent Special Interlocutor for Missing Children and Unmarked Graves and Burial Sites associated with Indian Residential Schools (justice.gc.ca)](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.justice.gc.ca%2Feng%2Finterlocutor-interlocuteur%2Findex.html&data=05%7C02%7CSonya.Driscoll%40dfo-mpo.gc.ca%7Cef161e97b9934cf6a6b608dc436c3135%7C1594fdaea1d94405915d011467234338%7C0%7C0%7C638459379168033624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ZdgV8zKoTKAYn8BU5iL%2BGVTlxKhhBTGofhDDUEcxEn4%3D&reserved=0). [Home \| Office of the Special Interlocutor (osi-bis.ca)](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fosi-bis.ca%2F&data=05%7C02%7CSonya.Driscoll%40dfo-mpo.gc.ca%7Cef161e97b9934cf6a6b608dc436c3135%7C1594fdaea1d94405915d011467234338%7C0%7C0%7C638459379168044594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=CxqyUyj4pkgVIgU10o2GeHtGu0yBiAEcKmsWM7qXNjA%3D&reserved=0)*

<embed src="sep27.pdf" type="application/pdf" width="100%" height="600px" />


# ***5-Day Kesalul! ReconciliACTION 2024 Mawio’mi***

## September 30^rd^ – October 4^th^, 2024

**September 30^th^, 2024 - Campus-Community TEACH-IN on the National Day for Truth and Reconciliation.**

-   8:00 a.m.: **Raising of the Tipi** in Clock Park with Acadia students and Elder Dr. Joe Michael. **Festival Theatre Day-long Art and Craft Showcase and Sale**.

-   Morning Birch Bark Canoe and Art Showcase by Melissa Sue Labrador & Todd Labrador.

-   Day-long Art Showcase and Dialogue by Dr. Gerald Gloade and Lily-Beth Fisher.

-   Join in the co-creation of the Kesalul I-WIL Too! ReconciliACTION Quilt.

-   8:30 a.m.: **Opening Ceremony** by Elder Dr. Lorraine Peters-Whitman followed by Words of Welcome, Festival Theatre.

-   9 – 10 a.m.: **“Storytelling through Art”** with Dr. Gerald Gloade and Lily-Beth Fisher, co-creators of the 2021 BEFORE Mural and the 2024 Kesalul:  ReconciliACTION Art Series.

-   10 – 11 a.m. Keynote: “**Reconciliation in Mi'kma'ki”**by Elder Dr. Lorraine Peters-Whitman.

-   11 – 12 p.m. Keynote: **“From 7th Generation to 7 Generations: Understanding our Role, Place and Responsibilities to Culture, Traditional Knowledge, and Conservation in a changing environment”** with Melissa Sue Labrador & Todd Labrador, Theatre Festival.

-   1:30 – 2:30 p.m. Keynote: “**Beyond Colonialism”** by Inuk Elder, Dr. Piita Irniq, former Commissioner of Nunavut, Residential “school” Survivor.

*Peter T. Irniq, born in 1947, is an Inuit cultural teacher and consultant, who has lived most of his life in the Kivalliq Region of Nunavut. He has also lived in the Northwest Territories, Manitoba and presently lives in Ottawa, Ontario. Mr. Irniq served two terms in the Territorial Council of the N.W.T. representing the Keewatin Region riding (1975-79) where he held portfolios of Social Development, Economic Development and Tourism and Natural and Cultural Affairs and the riding of Aivilik (1987-91), as regular member he fought to have Inuit represented at higher levels of the Civil Service, pursue higher education and have a greater presence in business. Mr. Irniq has worked for the Public Service of Northwest Territories and Nunavut in various capacities. Mr. Irniq became Deputy Minister of Culture, Language, Elders and Youth in the new Government of Nunavut in 1998 with a mandate of guardianship of traditional Inuit culture and language. His next challenge was to set up the offices of the Official Languages, Access to Information and the Conflict of Interest Commissioners. In April 2000 Mr. Irniq was appointed the Commissioner of Nunavut and served the five-year term. He remained active in the promotion of, preservation of culture and language through Inuit Qaujimajatuqangit (Inuit Traditional Knowledge) and to work with elders and youth to promote the pride and commitment of our unique culture and language. Mr. Irniq presently sits on The Museum of History on Aboriginal Advisory Committee; as a consultant he has participated in Conferences such as Inuit Studies in Paris; traveled to China and Mongolia at the invitation of the Embassy; writes and counsels on Inuit language and culture; entertains through drum dancing and building Inuksuit.*

-   2:45 – 4 p.m.: **Love and ReconciliACTION Panel** with Indigenous Experts and Settler Allies: Darlene Peters Copeland; Poppy Conley, Sandy Fisher; Kayla Mansfield Brown; Lara Hartman; Lily-Beth Fisher; Ana Martin; Holly Meuse; Lagina Morse; Mary Nicholas; Brooke Paul; Elder Ella Paul; Gene Saleski; Sherri Springle; Debbie Toney; TJ Wilson.

-   4 - 5 p.m. Keynote: **Impact and Reclamation as the Third Generation** by Lara Hartman, Granddaughter of a Residential “school” Survivor, Acadia University alum

-   *Lara’s grandmother was one of the more than 150,000 Indigenous children that were taken away from their homes and families to a residential school. Now we are in a place of reconciliation through healing and hope. Hope for the future. Hope for things to get better. For the past nearly 10 years, Lara has been working on reclaiming her identity and embracing her culture. Reclamation through reading, asking questions, attending events in the Indigenous communities close to Fraser Lake, British Columbia and listening to the voices of Indigenous peoples around her who she can learn from.*

-   5 p.m.: Words of appreciationfollowed by a Closing Ceremony by Elder Dr. Joe Michael.

<embed src="sep30.pdf" type="application/pdf" width="100%" height="600px" />


## **October 1^st^, 2024 - Treaty Day in Nova Scotia!**

-   **Students’ Policy Dialogue with Indigenous Experts**

-   Indigenous Expert: Lara Hartman

-   1 – 2:20 (KCIC Classroom) and 4 – 5:20 (KCIC Classroom 12, the Auditorium).

-   **Public Keynote: Decolonizing Education: Removing the Blinders**

-   Focus: As Honourable Justice Murray Sinclair, Chair of the Truth and Reconciliation Commission said in 2016, “Education got us into this mess and education will get us out of it”. Despite education institutions efforts through things like land acknowledgements and events, there is still much more to accomplish for the educational systems in Canada to truly be decolonized. Lara has worked with a BC School District and the Maple League of Universities on this idea of decolonizing education and Indigenizing what is on the curriculum or in the syllabi.

-   Indigenous Expert: **Lara Hartman**

-   6:30 – 8 pm - Fountain Commons.

<embed src="oct1.pdf" type="application/pdf" width="100%" height="600px" />


## **October 2^nd^, 2024.**

-   **Constructing Critical Hope for ReconciliACTION: Building an Inuksuk at Acadia University**

-   Lend a hand, have tea and a chat with Dr. Piita Irniq as the construction of an Inuksuk art installation continues in front of the library (BAC) at Acadia University

-   **Interactive Art Installation:** Students in Professor Leidl’s class, Art 3033: Art and Identity, create a Kesalul! I-WIL Commit to ReconciliACTION art installation for you to explore and enjoy, called ***The Poetic Tree: Embracing Our Nature**.*

-   **Description:** Acadia University students delve into their thoughts and feelings about climate change and their own identity in connection to nature. This includes an exploration of childhood to the present memories and experiences. It is done by choosing a tree they feel most connected to and writing a two-page poem about their tree and weaving it altogether. The poems will be temporarily attached to trees. This event is an interactive installation and includes poetry reading, embracing of personal trees and those of others. This is a powerful symbolic gesture of acceptance of differences and love of self, others and the very trees that nurture us.

-   1:30 pm to 3:30 pm - walk along the Woodland Trails to enjoy the students’ interactive artistic installation.

-   **Students’ Policy Dialogue with Indigenous Experts Public Keynote Talk: ReconciliACTION and the Calls to Justice of the Missing and Murdered Indigenous Women and Girls National Inquiry**

-   Indigenous Expert: Elder Dr. Lorraine Peters-Whitman, former President of the NWAC & Darlene Peters Copeland, Indigenous Programming and Recruitment Advisor, Student Services at Acadia University

-   6:30 – 8 pm - Fountain Commons

<embed src="oct2.pdf" type="application/pdf" width="100%" height="600px" />


## **October 3^rd^, 2024.**

-   **Constructing Critical Hope for ReconciliACTION: Building an Inuksuk at Acadia University**

-   Lend a hand, have tea and a chat with Dr. Piita Irniq as the construction of an Inuksuk art installation continues in front of the library (BAC) at Acadia University.

-   [**Students’ Policy Dialogue with Indigenous Experts**]{.underline}

-   Indigenous Expert: Elder Dr. Piita Irniq and Lara Hartman.

-   1 – 2:20 (KCIC Classroom) and 4 – 5:20 (KCIC Auditorium).

-   **Past, Present, Future Talking Circle** with Indigenous Elders together Acadia U Alumni and Current Campus Students and local Indigenous Youth and Children

-   Moderators: Darlene Peters Copeland and Ann Sylliboy

-   Elders: Elder Dr. Joe Michael, Elder Dr. Lorraine Peters-Whitman, Dr. Piita Irniq

-   Acadia U Alumni, Current Acadia U students, and Indigenous Children and Youth (TBD) including Taylor Baker; Kayla Mansfield Brown; Savannah Frances; Lara Hartman; Ana Martin; Mary Nicholas; Holly Meuse; Gene Saleski; Sherri Springle; Deb Toney.

-   5:30 – 8 p.m. - Fountain Commons Great Room

<embed src="oct3.pdf" type="application/pdf" width="100%" height="600px" />


**October 4^th^, 2021 - The National Sisters and Brothers in Spirit Day of Vigils for Missing and Murdered Indigenous Peoples.**

-   **Day-long Art Showcase by and Dialogue with Dr. Gerald Gloade and Lily-Beth Fisher**

-   Co-creation of the *Kesalul, I-WIL Too! ReconciliACTION Quilt*

-   9:45 a.m.: Opening Prayer and Words of Welcome

-   10 – 11 a.m.: ***The Highway of Tears: North Central BC and Missing and Murdered Indigenous Women and Girls,*** Indigenous Expert Keynote with Lara Hartman.

Growing up, Lara heard stories about the tragedy and was always told not to hitch-hike and to be careful along the highway. As a child, she understood but did not comprehend as much as she does now. Although Missing and Murdered Indigenous Women and Girls are an ongoing tragedy across Canada from coast to coast to coast, but Lara will be talking about BC, specifically the Highway of Tears. The Highway of Tears is another name for a stretch of Highway 16 in North-Central British Columbia. This part of the highway runs from Prince George to Prince Rupert, covering 724 kilometers. In order to come to a place where Indigenous women and girls are safe and do not need to live in fear, we must look to the structures that are responsible for allowing these atrocities to happen. We need to acknowledge that it is structural and come to terms with an answer. I do have hope though, because without hope, what do we really have?

-   11 – 12 noon: **Flash Circle** – Show up to the Acadia U Quad wearing something red

-   12:30 – 2 p.m.: **Reflections** from Elder Dr. Joe Michael, Elder Dr. Lorraine Peters-Whitman, Elder Ella Paul, Elder Dr. Piita Irniq, Ann Sylliboy, Brooke Paul, Holly Meuse, Kayla Mansfield-Brown, Lara Hartman, Debbie Toney, Mary Nicholas, Poppy Conley

-   2 – 2:30 p.m.: **Unveiling the Inuksuk created by Dr. Piita Irniq for Acadia University.**

-   2:30 pm: Closing Ceremony.

# ***I-WIL Too! Commit to ReconciliACTION Fall 2024 Acadia University Students’ Policy Dialogue with Indigenous Experts***

<embed src="oct4.pdf" type="application/pdf" width="100%" height="600px" />


## **October 24^th^, 2024.**

-   **Students’ Policy Dialogue with Indigenous Experts**

-   Indigenous Expert: Rosemary Cooper, Executive Director of Pauktuutit, the National Inuit Women’s Advocacy Organization.

-   Time & Location: 1 – 2:20 (KCIC Classroom 14) and 4 – 5:20 (KCIC Classroom 21, the Auditorium)

-   **Public Keynote: Policy and Research - a New Path forward for Pauktuuti**

-   Partner: Ann Sylliboy (MK)

-   Indigenous Expert: **Rosemary Cooper**, Executive Director of Pauktuutit, the National Inuit Women’s Advocacy Organization.

*Since joining Pauktuutit in 2016, Rosemary has built a legacy of providing inspiring leadership to Pauktuutit’s policy, programs, and communications teams to achieve progress on the Board’s resolutions and priorities. As well, she has deep experience advocating for the interests of Inuit women and girls to officials in federal government departments and agencies. Rosemary also has a strong track record of working collaboratively with Inuit partners in Inuit Nunangat, in urban centres and at the national level. Rosemary led Inuit Tapiriit Kanatami’s work with the Truth and Reconciliation Commission. She also represented Pauktuutit from the inception of the National Inquiry into Missing and Murdered Indigenous Women and Girls (MMIWG) through to the release of the final report, with 46 Inuit-specific Calls for Justice. Rosemary is now Pauktuutit’s representative on the Core Working Group for the co-development of the MMIWG National Action Plan, with the Government of Canada. Prior to joining Pauktuutit, Rosemary held senior portfolios in the Government of Nunavut, including Director of Social Programs at the Office of the Interim Commissioner; Assistant Deputy Minister, Department of Health and Social Services; and Assistant Deputy Minister, Executive and Intergovernmental Affairs. She has also served as a Political Advisor at Inuit Tapiriit Kanatami (ITK). Born and raised in Iqaluit, Nunavut, Rosemary is Inuk and fluent in Inuktut and English. Her progressive career achievements have contributed to her profile as an expert in Inuit affairs. This experience includes advocacy and leadership for the development of policy, legislation, and programs to strengthen violence prevention, community policing, investments in social services and health care and the promotion of Inuit arts and culture. Over the past 30 years, Rosemary’s work with international, national, territorial, and regional organizations and bodies has included: The United Nations Commission on Status of  Women, The United Nations Secretariat of the Permanent Forum on Indigenous Issues, The Federation of Councils, the Office of the Governor General of Canada, the Inuit Crown Partnership Committee, the National Inuit Housing Working Group and the Canadian Millennium Scholarship Foundation. Championing the human rights of Inuit women and girls, including the protection and support of women and children fleeing violence, are passions central to Rosemary’s work.*

-   *6:30 – 8 pm -* Fountain Commons

<embed src="oct24.pdf" type="application/pdf" width="100%" height="600px" />


## **October 31^st^, 2024.**

-   **Lunchtime Keynote: ReconciliACTION – Your Role.**

-   Indigenous Expert: **Kory Wilson**

*Puglid (Kory Wilson, BSc. JD) is Kwakwaka’wakw. She is the Executive Director of Indigenous Initiatives and Partnerships for British Columbia Institute of Technology. She is also Chair of the BC First Nations Justice Council. Kory is a member of the BC Law Society and practiced criminal defense and family law. She is Chair of the World Federation of Colleges and Polytechnics Indigenous Affinity Group. Kory has over 20 years of experience in post-secondary education, community development, and legal profession. Good governance and making systemic change are specialties and changing the Criminal Justice system and revitalizing Indigenous Justice are passions. She has served on several boards from Pearson College, BC Women’s Foundation, Genome BC and currently serves on the Downie Wenjack Fund, Future Skills Canada, West Point Grey Academy and the BC Conservation Fund. A sought-after speaker and strategist on advancing and ‘truth-telling’ about the past and moving forward towards Reconciliation. With a deep commitment to justice and education, both formal and informal, she knows innovative and creative solutions are a must to move Reconciliation into ReconciliACTION. Education and access to knowledge are key to move everyone forward. When people know better, they do better. Diversity is a reality, but inclusion is a choice. Inclusion requires bold and courageous conversations and confidence to ensure systemic change and outside the box solutions. We can and must do better – Canada can and must do better. Together we are stronger*

-   11:30 – 12:45 pm - Fountain Commons

-   **Students’ Dialogue with Kory Wilson**

-   1 – 2:20 and 4 – 5:15 - Fountain Commons

***I-WIL Too! Commit to ReconciliACTION Student Public Showcase & Expert Feedback Workshop***

<embed src="oct31.pdf" type="application/pdf" width="100%" height="600px" />


## **November 1^st^, 2024.**

-   **Day-long Art Showcase by and Dialogue with Dr. Gerald Gloade and Lily-Beth Fisher,** co-creators of the Kesalul! ReconciliACTION Art Series.

-   Indigenous Panel of Experts:  Elder Dr. Joe Michael, Elder Dr. Lorraine Peters-Whitman, Brooke Paul, Darlene Peters Copeland, Ann Sylliboy (MK)

-   9 a.m. - 3 p.m. - KCIC Seminar Room.

***Kesalul! I-WIL Too: ReconciliACTION Debriefing Workshop, Student Showcase, and Gala Finale***

<embed src="nov1.pdf" type="application/pdf" width="100%" height="600px" />

## **November 21^st^, 2024**

**Debriefing Workshop**

Dialogue with Kesalul! ReconciliACTION artists, Dr. Gerald Gloade and Lily-Beth Fisher.

Dialogue with MK Partner, Ann Sylliboy.

Dialogue with the CEWIL Team.

-   3 – 5 p.m. - Fountain Commons.

**Student Showcase** and Light Supper

-   5 – 6:30 p.m. - Fountain Commons

-   **Gala Finale**

-   6:30 – 8:30 p.m. - Fountain Commons

-   Opening Remarks: Ann Sylliboy (MK) and the CEWIL Team

-   **Keynote:** **“ReconciliACTION: The Importance of Indigenous Knowledge in Academia”**

-   Indigenous Expert: **Taylor Baker**, Executive Council Member, Tsawwassen First Nation, Acadia University Alumnus.

*Taylor Baker is an Executive Councillor and Legislator for Tsawwassen First Nation (TFN). She is Indigenous with both Coast Salish and Gitxsan ancestry. Taylor was elected in 2022 at 26 years old for a 4-year term, also serving as Co-Chair for TFN’s Housing Advisory Committee. Taylor also worked on the Speaker’s Indigenous Reconciliation Advisory Committee that assisted in the development of the Legislative Assembly of British Columbia’s Reconciliation Action Plan release in May 2024. In 2019, she received her Bachelor of Arts in Politics from Acadia University.*

-   **Keynote:** **Reflections from Renowned Inuit Educator and Drum Dancer**

-   Indigenous Expert: **David Serkoak** from Arviat, Nunavut.

*David Serkoak was in born at Hicks Lake, Nunavut west of Arviat, Nunavut. David has worked in many levels in education as a teacher primary/secondary schools and vice-principal, principal, Instructor at Nunavut Arctic College, and as a curator at the British Museum of Mankind in England. David helped to develop Inuktitut teaching materials at all levels local, regional and territorial both in NWT and Nunavut. During his free time he spends his time making Inuit drums to many Arctic communities to the youth. In 2008, David retired from teaching but still very busy giving workshops on Inuit Social History to Civil Servants and several Universities in Ottawa area. He and his wife Lesley have three grown daughters, Amanda, Meeka and Karla. David spends many hours with his six grandchildren, Briana, Makayla, Kyle, Laura, Ryan and Emma. Summer of 2017, he was invited to drum dance at North Pole via Murmansk, Russia. In 2022, he was part of Indigenous delegation to Vatican as an Inuk elder and drum dancer. David is also past and founder of Ahiarmiut Relocation Society, It took 28 years to get Canada to apologize to the Ahiarmiut of forced relocations. In 2019, Ahiarmiut finally received their long-waited apology from Canada.*

-   **Unveiling the Kesalul! ReconciliACTION Art Series** co-created by Dr. Gerald Gloade and Lily-Beth Fisher.

-   Words of Appreciation.

-   Closing Prayer.

***I-WIL Too! Commit to ReconciliACTION Fall 2024 Students’ Policy Dialogue with Indigenous Experts***

<embed src="nov21.pdf" type="application/pdf" width="100%" height="600px" />

## **November 25^th^, 2024**

-   **Student Policy Dialogue and Celebration** with David Serkoak

-   1 – 3:50 p.m. - KCIC Classroom 14.

<embed src="nov25.pdf" type="application/pdf" width="100%" height="600px" />
